#!/usr/bin/env node
/* Put this app's own native code into the generated Android project.
 *
 * android/ is generated by `npx cap add android` and never committed (see the
 * app's package.json), so a hand-written plugin cannot simply live there. It
 * lives in app/native/android/ and this copies it in, next to MainActivity,
 * then registers it — Capacitor finds npm plugins by itself, but a plugin that
 * is part of the app must be registered in MainActivity before the bridge
 * starts.
 *
 * Run after `cap add android`, like patch-manifest.js. Idempotent.
 *
 * Usage: node scripts/add-native.js [path/to/app/android]
 */
const fs = require('fs');
const path = require('path');

const androidDir = process.argv[2] || path.join(__dirname, '..', 'app', 'android');
const sourceDir = path.join(__dirname, '..', 'app', 'native', 'android');
const PLUGINS = ['BatteryOptimisationPlugin'];

function findMainActivity(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findMainActivity(p);
      if (found) return found;
    } else if (entry.name === 'MainActivity.java') {
      return p;
    }
  }
  return null;
}

const javaRoot = path.join(androidDir, 'app', 'src', 'main', 'java');
if (!fs.existsSync(javaRoot)) {
  console.error(`No Android project at ${androidDir}. Run "npx cap add android" in app/ first.`);
  process.exit(1);
}
const mainActivity = findMainActivity(javaRoot);
if (!mainActivity) {
  console.error(`No MainActivity.java under ${javaRoot}.`);
  process.exit(1);
}

// The plugin sources declare the package they belong in. It must be the one
// MainActivity is in, or the build fails on a class it cannot find — better to
// fail here, saying why.
const activitySrc = fs.readFileSync(mainActivity, 'utf8');
const pkg = (activitySrc.match(/^package\s+([\w.]+);/m) || [])[1];
for (const name of PLUGINS) {
  const src = fs.readFileSync(path.join(sourceDir, `${name}.java`), 'utf8');
  const srcPkg = (src.match(/^package\s+([\w.]+);/m) || [])[1];
  if (srcPkg !== pkg) {
    console.error(`${name}.java is in package ${srcPkg} but MainActivity is in ${pkg}. `
      + 'Change the package line in app/native/android to match capacitor.config.json appId.');
    process.exit(1);
  }
  fs.writeFileSync(path.join(path.dirname(mainActivity), `${name}.java`), src);
}

// Registration has to happen before super.onCreate, which is when the bridge
// starts and the list of plugins is fixed.
const registrations = PLUGINS.map((n) => `        registerPlugin(${n}.class);`).join('\n');
const activity = `package ${pkg};

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;

// Written by scripts/add-native.js — edit that script, not this file.
public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
${registrations}
        super.onCreate(savedInstanceState);
    }
}
`;
fs.writeFileSync(mainActivity, activity);
console.log(`Added ${PLUGINS.join(', ')} and registered ${PLUGINS.length === 1 ? 'it' : 'them'} in ${mainActivity}.`);
